services:
  postgres:
    image: postgres:15
    container_name: finance-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - finance-network

# PgAdmin para visualizar o banco :)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: finance-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finance.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - finance-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  finance-network:
    driver: bridge